// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("DriverTool.x86.Host")>]
[<assembly: AssemblyDescriptionAttribute("Host process providing DriverTool with 32-bit services.")>]
[<assembly: AssemblyProductAttribute("DriverTool.x86.Host")>]
[<assembly: AssemblyCompanyAttribute("github/trondr")>]
[<assembly: AssemblyCopyrightAttribute("Copyright © github/trondr 2018-2021")>]
[<assembly: AssemblyVersionAttribute("1.0.21087.50")>]
[<assembly: AssemblyFileVersionAttribute("1.0.21087.50")>]
[<assembly: ComVisibleAttribute(false)>]
[<assembly: GuidAttribute("19822aea-c088-455d-b5a5-4738a3a9dba9")>]
[<assembly: InternalsVisibleToAttribute("DriverTool.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "DriverTool.x86.Host"
    let [<Literal>] AssemblyDescription = "Host process providing DriverTool with 32-bit services."
    let [<Literal>] AssemblyProduct = "DriverTool.x86.Host"
    let [<Literal>] AssemblyCompany = "github/trondr"
    let [<Literal>] AssemblyCopyright = "Copyright © github/trondr 2018-2021"
    let [<Literal>] AssemblyVersion = "1.0.21087.50"
    let [<Literal>] AssemblyFileVersion = "1.0.21087.50"
    let [<Literal>] ComVisible = false
    let [<Literal>] Guid = "19822aea-c088-455d-b5a5-4738a3a9dba9"
    let [<Literal>] InternalsVisibleTo = "DriverTool.Tests"
