// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("DriverTool")>]
[<assembly: AssemblyDescriptionAttribute("Download drivers and software for a specific PC model and create a driver package that can be imported into SCCM as a package or application.")>]
[<assembly: AssemblyProductAttribute("DriverTool")>]
[<assembly: AssemblyCompanyAttribute("github/trondr")>]
[<assembly: AssemblyCopyrightAttribute("Copyright © github/trondr 2018-2019")>]
[<assembly: AssemblyVersionAttribute("1.0.19064.12")>]
[<assembly: AssemblyFileVersionAttribute("1.0.19064.12")>]
[<assembly: ComVisibleAttribute(false)>]
[<assembly: GuidAttribute("19822aea-c088-455d-b5a5-4738a3a9dba7")>]
[<assembly: InternalsVisibleToAttribute("DriverTool.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "DriverTool"
    let [<Literal>] AssemblyDescription = "Download drivers and software for a specific PC model and create a driver package that can be imported into SCCM as a package or application."
    let [<Literal>] AssemblyProduct = "DriverTool"
    let [<Literal>] AssemblyCompany = "github/trondr"
    let [<Literal>] AssemblyCopyright = "Copyright © github/trondr 2018-2019"
    let [<Literal>] AssemblyVersion = "1.0.19064.12"
    let [<Literal>] AssemblyFileVersion = "1.0.19064.12"
    let [<Literal>] ComVisible = false
    let [<Literal>] Guid = "19822aea-c088-455d-b5a5-4738a3a9dba7"
    let [<Literal>] InternalsVisibleTo = "DriverTool.Tests"
