//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriverTool.x86.Client.ToolServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ToolServiceReference.IToolService")]
    public interface IToolService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToolService/GetWebPageContent", ReplyAction="http://tempuri.org/IToolService/GetWebPageContentResponse")]
        string GetWebPageContent(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToolService/GetWebPageContent", ReplyAction="http://tempuri.org/IToolService/GetWebPageContentResponse")]
        System.Threading.Tasks.Task<string> GetWebPageContentAsync(string url);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IToolServiceChannel : DriverTool.x86.Client.ToolServiceReference.IToolService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ToolServiceClient : System.ServiceModel.ClientBase<DriverTool.x86.Client.ToolServiceReference.IToolService>, DriverTool.x86.Client.ToolServiceReference.IToolService {
        
        public ToolServiceClient() {
        }
        
        public ToolServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ToolServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ToolServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ToolServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetWebPageContent(string url) {
            return base.Channel.GetWebPageContent(url);
        }
        
        public System.Threading.Tasks.Task<string> GetWebPageContentAsync(string url) {
            return base.Channel.GetWebPageContentAsync(url);
        }
    }
}
