// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("DriverTool.Library")>]
[<assembly: AssemblyDescriptionAttribute("Library providing common DriverTool functionality.")>]
[<assembly: AssemblyProductAttribute("DriverTool.Library")>]
[<assembly: AssemblyCompanyAttribute("github/trondr")>]
[<assembly: AssemblyCopyrightAttribute("Copyright © github/trondr 2018-2021")>]
[<assembly: AssemblyVersionAttribute("1.0.21290.62")>]
[<assembly: AssemblyFileVersionAttribute("1.0.21290.62")>]
[<assembly: ComVisibleAttribute(false)>]
[<assembly: GuidAttribute("19822aea-c088-455d-b5a5-4738a3a9dba8")>]
[<assembly: InternalsVisibleToAttribute("DriverTool.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "DriverTool.Library"
    let [<Literal>] AssemblyDescription = "Library providing common DriverTool functionality."
    let [<Literal>] AssemblyProduct = "DriverTool.Library"
    let [<Literal>] AssemblyCompany = "github/trondr"
    let [<Literal>] AssemblyCopyright = "Copyright © github/trondr 2018-2021"
    let [<Literal>] AssemblyVersion = "1.0.21290.62"
    let [<Literal>] AssemblyFileVersion = "1.0.21290.62"
    let [<Literal>] ComVisible = false
    let [<Literal>] Guid = "19822aea-c088-455d-b5a5-4738a3a9dba8"
    let [<Literal>] InternalsVisibleTo = "DriverTool.Tests"
